<?php
/**
* Gauge_GoogleAnalytics
* Base Google Analytics snippet
*
* @var $block Gauge\GoogleAnalytics\Block\Analytics
*/
?>

<?php if ($block->isGoogleAnalyticsEnabled()) : ?>
<script name="gauge-ga">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    require([ 'jquery', 'jquery/ui'], function($){ 
        $(document).ready(function() {
            ga('create', '<?php echo $block->getGoogleAnalyticsId() ?>', 'auto');
            ga('require', 'ec');
            if ($('script[name="ec-pageview"]').length == 0) {
                ga('send', 'pageview');
            }
        });
    });
</script>
<?php endif; ?>